# Generated by Django 4.2.11 on 2024-03-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='message',
            new_name='content',
        ),
    ]
