# Generated by Django 4.2.11 on 2024-03-16 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_message_file_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Blog',
        ),
    ]
