# Generated by Django 4.2.11 on 2024-03-16 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_file_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='File',
        ),
    ]
