# Generated by Django 4.2.11 on 2024-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='public_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
